@echo off
echo --- JINX THEOREM: EXPERIMENTAL SUITE ---
echo 1. Running Square Scan...
python jinx_square.py
echo 2. Running Riemann Alignment...
python riemann.py
echo 3. Running Millionaire Scan...
python millionaire_scan.py
echo 4. Running Diagnostic Device...
python diagdevice.py
echo --- ALL TESTS COMPLETED ---
pause